import os
import logging
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from ..config import settings

logger = logging.getLogger(__name__)

class ReportGenerator:
    """Professional medical PDF report generator for Aviothic AI Platform.
    
    Creates doctor-grade reports with patient information, predictions,
    confidence scores, risk assessments, and visualizations.
    """
    
    def __init__(self):
        # Ensure reports directory exists
        self.reports_dir = os.path.join(settings.STATIC_DIR, 'reports')
        os.makedirs(self.reports_dir, exist_ok=True)
        
    def generate_medical_report(self, case_id: str, user_email: str, prediction_data: dict, image_path: str, gradcam_path: str) -> str:
        """Generate professional medical PDF report.
        
        Args:
            case_id: Unique case identifier
            user_email: Email of user who submitted
            prediction_data: Dictionary with prediction results
            image_path: Path to original image
            gradcam_path: Path to GradCAM visualization
            
        Returns:
            Path to generated PDF report
        """
        try:
            # Define report filename
            filename = f"report_{case_id}.pdf"
            report_path = os.path.join(self.reports_dir, filename)
            
            # Create PDF document
            doc = SimpleDocTemplate(
                report_path,
                pagesize=letter,
                rightMargin=72,
                leftMargin=72,
                topMargin=72,
                bottomMargin=18
            )
            
            # Container for the 'Flowable' objects
            story = []
            
            # Get styles
            styles = getSampleStyleSheet()
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=24,
                spaceAfter=30,
                alignment=1,  # Center alignment
                textColor=colors.darkblue
            )
            
            heading_style = ParagraphStyle(
                'CustomHeading',
                parent=styles['Heading2'],
                fontSize=14,
                spaceAfter=12,
                textColor=colors.darkgreen
            )
            
            # Add title
            title = Paragraph("AVIOTHIC AI MEDICAL REPORT", title_style)
            story.append(title)
            story.append(Spacer(1, 12))
            
            # Add patient information
            patient_info_data = [
                ["Patient ID", case_id],
                ["Generated By", user_email],
                ["Timestamp", datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")]
            ]
            
            patient_table = Table(patient_info_data, colWidths=[2*inch, 4*inch])
            patient_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            
            story.append(Paragraph("PATIENT INFORMATION", heading_style))
            story.append(patient_table)
            story.append(Spacer(1, 12))
            
            # Add prediction results
            prediction_data_table = [
                ["Prediction Result", prediction_data.get('prediction', 'N/A')],
                ["Confidence Score", f"{prediction_data.get('confidence', 0)*100:.2f}%"],
                ["Risk Assessment", f"{prediction_data.get('risk_score', 0)}/100"],
                ["BI-RADS Category", prediction_data.get('birads_class', 'N/A')],
                ["Lesion Type", prediction_data.get('lesion_type', 'N/A')],
                ["Breast Density", prediction_data.get('breast_density', 'N/A')],
                ["AI Explanation", prediction_data.get('explanation', 'N/A')]
            ]
            
            pred_table = Table(prediction_data_table, colWidths=[2*inch, 4*inch])
            pred_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 10),
                ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            
            story.append(Paragraph("PREDICTION RESULTS", heading_style))
            story.append(pred_table)
            story.append(Spacer(1, 12))
            
            # Add images if available
            if os.path.exists(image_path):
                story.append(Paragraph("ORIGINAL IMAGE", heading_style))
                im = Image(image_path, width=4*inch, height=4*inch)
                story.append(im)
                story.append(Spacer(1, 12))
            
            if os.path.exists(gradcam_path):
                story.append(Paragraph("GRAD-CAM VISUALIZATION", heading_style))
                gc_im = Image(gradcam_path, width=4*inch, height=4*inch)
                story.append(gc_im)
                story.append(Spacer(1, 12))
            
            # Add doctor review section
            story.append(Paragraph("DOCTOR REVIEW SECTION", heading_style))
            story.append(Paragraph("Doctor's Notes:", styles['Normal']))
            story.append(Spacer(1, 24))
            story.append(Paragraph("Doctor's Confirmation:", styles['Normal']))
            story.append(Spacer(1, 24))
            story.append(Paragraph("Doctor's Signature:", styles['Normal']))
            story.append(Spacer(1, 24))
            
            # Add footer
            story.append(Spacer(1, 24))
            footer_text = f"Report generated by Aviothic AI Medical Imaging Platform on {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}"
            story.append(Paragraph(footer_text, styles['Italic']))
            
            # Build PDF
            doc.build(story)
            
            logger.info(f"Medical report generated successfully: {report_path}")
            return report_path
            
        except Exception as e:
            logger.error(f"Failed to generate medical report for case {case_id}: {e}")
            raise

# Global report generator instance
report_generator = ReportGenerator()

__all__ = ["report_generator", "ReportGenerator"]