from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
import io, base64, os
from PIL import Image

def generate_report(output_path, patient_id, prediction, probabilities, gradcam_b64):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4
    c.setFont('Helvetica-Bold', 18)
    c.drawString(1*inch, height - 1*inch, 'Aviothic.ai — Diagnostic Report')
    c.setFont('Helvetica', 12)
    c.drawString(1*inch, height - 1.4*inch, f'Patient ID: {patient_id}')
    c.drawString(1*inch, height - 1.7*inch, f'Prediction: {prediction}')
    c.drawString(1*inch, height - 2.0*inch, f'Probabilities: {probabilities}')
    if gradcam_b64:
        imgdata = base64.b64decode(gradcam_b64)
        img = Image.open(io.BytesIO(imgdata))
        img_path = '/tmp/gradcam_preview.png'
        img.save(img_path)
        c.drawImage(img_path, 1*inch, height - 6*inch, width=4*inch, preserveAspectRatio=True, mask='auto')
    c.setFont('Helvetica-Oblique', 9)
    c.drawString(1*inch, 0.6*inch, 'This report is generated by Aviothic.ai — for clinical use after validation.')
    c.save()

if __name__ == '__main__':
    generate_report('static/sample_report.pdf', 'TEST123', 'Benign', [0.85, 0.15], None)
    print('sample_report.pdf written')